# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-24 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text=b'\xe4\xb8\x8d\xe9\x9c\x80\xe8\xa6\x81\xe5\x8a\xa0 https', max_length=100)),
                ('ahead_days', models.IntegerField(default=7, help_text=b'\xe6\x8f\x90\xe5\x89\x8d\xe5\x87\xa0\xe5\xa4\xa9\xe6\x8f\x90\xe9\x86\x92')),
                ('email', models.TextField(blank=True)),
                ('expire_at', models.DateField(blank=True, help_text=b'\xe8\xbf\x87\xe6\x9c\x9f\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('extra', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
