# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-12 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athenatools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x8e\x9f\xe6\x9d\x90\xe6\x96\x99\xe5\x90\x8d\xe7\xa7\xb0')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name=b'\xe8\xa7\x84\xe6\xa0\xbc')),
                ('quantity', models.CharField(blank=True, max_length=255, verbose_name=b'\xe9\x87\x87\xe8\xb4\xad\xe6\x95\xb0\xe9\x87\x8f')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8d\x95\xe4\xbd\x8d/\xe8\xbf\x9b\xe5\x8f\xa3\xe4\xbb\xa3\xe7\x90\x86\xe5\x95\x86')),
                ('produced_at', models.CharField(blank=True, max_length=255, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe6\x97\xa5\xe6\x9c\x9f')),
                ('exp', models.CharField(blank=True, max_length=255, verbose_name=b'\xe4\xbf\x9d\xe8\xb4\xa8\xe6\x9c\x9f')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86')),
                ('receipt', models.CharField(blank=True, max_length=255, verbose_name=b'\xe7\xb4\xa2\xe8\xaf\x81\xe7\xb4\xa2\xe7\xa5\xa8')),
                ('expired_quantity', models.CharField(blank=True, max_length=255, verbose_name=b'\xe8\xbf\x87\xe6\x9c\x9f\xe5\xa4\x84\xe7\x90\x86\xe6\x95\xb0\xe9\x87\x8f')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xbd\x95\xe5\x85\xa5\xe8\x80\x85')),
            ],
        ),
    ]
