# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='day',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=b'\xe9\x87\x87\xe8\xb4\xad\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
