# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0002_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8d\x95\xe4\xbd\x8d/\xe8\xbf\x9b\xe5\x8f\xa3\xe4\xbb\xa3\xe7\x90\x86\xe5\x95\x86'),
        ),
    ]
