# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0003_auto_20181128_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'', verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe8\xaf\x8d')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6587\u6863',
                'verbose_name_plural': '\u6587\u6863',
            },
        ),
    ]
