# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=b'', verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6'),
        ),
    ]
