# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-30 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0006_auto_20181129_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_consume',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe5\x87\xba\xe8\xb4\xa7'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athenatools.Product', verbose_name=b'\xe5\x8e\x9f\xe6\x9d\x90\xe6\x96\x99'),
        ),
    ]
