# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0008_auto_20181203_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
    ]
