# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-12 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athenatools', '0009_auto_20181210_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('keys', models.TextField(blank=True, help_text=b'\xe5\x8f\xaf\xe9\x85\x8d\xe7\xbd\xae\xe5\xa4\x9a\xe4\xb8\xaa,\xe6\xaf\x8f\xe4\xb8\xaa\xe4\xb8\x80\xe8\xa1\x8c,\xe7\x95\x99\xe7\xa9\xba\xe8\xa1\xa8\xe7\xa4\xba\xe4\xb8\x8d\xe9\x9c\x80\xe8\xa6\x81\xe5\xaf\x86\xe9\x92\xa5\xe5\xb0\xb1\xe5\x8f\xaf\xe6\x9f\xa5\xe7\x9c\x8b', verbose_name=b'\xe6\x9f\xa5\xe7\x9c\x8b\xe5\xaf\x86\xe9\x92\xa5')),
                ('content', models.TextField(blank=True, default=b"EXAMPLE_KEY = 'XXX'", help_text=b'\xe7\x9b\xb4\xe6\x8e\xa5\xe5\x86\x99 python \xe8\x84\x9a\xe6\x9c\xac', verbose_name=b'\xe8\x84\x9a\xe6\x9c\xac\xe5\x86\x85\xe5\xae\xb9')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x8b\xa5\xe6\x9c\x89\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u811a\u672c',
                'verbose_name_plural': '\u914d\u7f6e\u811a\u672c',
            },
        ),
        migrations.AlterUniqueTogether(
            name='settingscript',
            unique_together=set([('user', 'name')]),
        ),
    ]
