# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0012_auto_20181220_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settingscript',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='settingscript',
            name='user',
        ),
        migrations.AddField(
            model_name='certreminder',
            name='err',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='SettingScript',
        ),
    ]
