# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0013_auto_20190102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=b'docs', verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6'),
        ),
    ]
