# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athenatools', '0014_auto_20190112_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cmd', models.TextField(blank=True, default=b'cd /myproj && git pull && runserver')),
                ('remark', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='deployhistory',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athenatools.Deployment'),
        ),
    ]
